# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'swin_gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1031, 708)
        font = QtGui.QFont()
        font.setUnderline(False)
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_reset = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_reset.setGeometry(QtCore.QRect(760, 590, 261, 21))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.pushButton_reset.setFont(font)
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(760, 10, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setUnderline(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(760, 210, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setUnderline(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(760, 550, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setUnderline(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(760, 360, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setUnderline(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.pushButton_clear_terminal = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_clear_terminal.setGeometry(QtCore.QRect(760, 620, 261, 21))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.pushButton_clear_terminal.setFont(font)
        self.pushButton_clear_terminal.setObjectName("pushButton_clear_terminal")
        self.pushButton_stop = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_stop.setGeometry(QtCore.QRect(760, 650, 261, 21))
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.pushButton_select_model_video = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_select_model_video.setGeometry(QtCore.QRect(760, 400, 261, 21))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.pushButton_select_model_video.setFont(font)
        self.pushButton_select_model_video.setObjectName("pushButton_select_model_video")
        self.pushButton_select_video = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_select_video.setGeometry(QtCore.QRect(760, 430, 261, 21))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.pushButton_select_video.setFont(font)
        self.pushButton_select_video.setObjectName("pushButton_select_video")
        self.pushButton_video_test = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_video_test.setGeometry(QtCore.QRect(760, 530, 261, 21))
        self.pushButton_video_test.setObjectName("pushButton_video_test")
        self.pushButton_image_test = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_image_test.setGeometry(QtCore.QRect(760, 340, 261, 21))
        self.pushButton_image_test.setObjectName("pushButton_image_test")
        self.pushButton_select_model_image = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_select_model_image.setGeometry(QtCore.QRect(760, 250, 261, 21))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.pushButton_select_model_image.setFont(font)
        self.pushButton_select_model_image.setObjectName("pushButton_select_model_image")
        self.pushButton_select_image = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_select_image.setGeometry(QtCore.QRect(760, 280, 261, 21))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.pushButton_select_image.setFont(font)
        self.pushButton_select_image.setObjectName("pushButton_select_image")
        self.pushButton_train = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_train.setGeometry(QtCore.QRect(760, 160, 261, 21))
        self.pushButton_train.setObjectName("pushButton_train")
        self.pushButton_select_config = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_select_config.setGeometry(QtCore.QRect(760, 130, 261, 21))
        self.pushButton_select_config.setObjectName("pushButton_select_config")
        self.pushButton_select_model_pretrained = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_select_model_pretrained.setGeometry(QtCore.QRect(760, 100, 261, 21))
        self.pushButton_select_model_pretrained.setObjectName("pushButton_select_model_pretrained")
        self.lineEdit_video_save_name = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_video_save_name.setGeometry(QtCore.QRect(840, 490, 141, 31))
        self.lineEdit_video_save_name.setObjectName("lineEdit_video_save_name")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(990, 500, 41, 18))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(760, 500, 81, 18))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 0, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 460, 731, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(740, 10, 20, 661))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(10, 30, 731, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 480, 731, 192))
        self.textBrowser.setObjectName("textBrowser")
        self.display = QtWidgets.QLabel(self.centralwidget)
        self.display.setGeometry(QtCore.QRect(10, 50, 731, 411))
        self.display.setText("")
        self.display.setObjectName("display")
        self.pushButton_select_config_image = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_select_config_image.setGeometry(QtCore.QRect(760, 310, 261, 21))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.pushButton_select_config_image.setFont(font)
        self.pushButton_select_config_image.setObjectName("pushButton_select_config_image")
        self.pushButton_select_config_video = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_select_config_video.setGeometry(QtCore.QRect(760, 460, 261, 21))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.pushButton_select_config_video.setFont(font)
        self.pushButton_select_config_video.setObjectName("pushButton_select_config_video")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_reset.setText(_translate("MainWindow", "Reset"))
        self.label.setText(_translate("MainWindow", "Training"))
        self.label_2.setText(_translate("MainWindow", "Image Test"))
        self.label_3.setText(_translate("MainWindow", "Reset"))
        self.label_4.setText(_translate("MainWindow", "Video Test"))
        self.pushButton_clear_terminal.setText(_translate("MainWindow", "Clear terminal"))
        self.pushButton_stop.setText(_translate("MainWindow", "Stop"))
        self.pushButton_select_model_video.setText(_translate("MainWindow", "Select model"))
        self.pushButton_select_video.setText(_translate("MainWindow", "Select video"))
        self.pushButton_video_test.setText(_translate("MainWindow", "Video test"))
        self.pushButton_image_test.setText(_translate("MainWindow", "Image test"))
        self.pushButton_select_model_image.setText(_translate("MainWindow", "Select model"))
        self.pushButton_select_image.setText(_translate("MainWindow", "Select image"))
        self.pushButton_train.setText(_translate("MainWindow", "Train"))
        self.pushButton_select_config.setText(_translate("MainWindow", "Select config"))
        self.pushButton_select_model_pretrained.setText(_translate("MainWindow", "Select pretrained model"))
        self.lineEdit_video_save_name.setText(_translate("MainWindow", "result"))
        self.label_5.setText(_translate("MainWindow", ".mp4"))
        self.label_6.setText(_translate("MainWindow", "Save name:"))
        self.label_7.setText(_translate("MainWindow", "SWIN - GUI"))
        self.pushButton_select_config_image.setText(_translate("MainWindow", "Select config"))
        self.pushButton_select_config_video.setText(_translate("MainWindow", "Select config"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

