# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1130, 932)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 740))
        font = QtGui.QFont()
        font.setUnderline(False)
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 0, 1, 5, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setMaximumSize(QtCore.QSize(291, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setUnderline(True)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.pushButton_set_parameters = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_set_parameters.sizePolicy().hasHeightForWidth())
        self.pushButton_set_parameters.setSizePolicy(sizePolicy)
        self.pushButton_set_parameters.setMaximumSize(QtCore.QSize(291, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_set_parameters.setFont(font)
        self.pushButton_set_parameters.setObjectName("pushButton_set_parameters")
        self.verticalLayout_2.addWidget(self.pushButton_set_parameters)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(291, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setUnderline(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.pushButton_select_model_pretrained = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_select_model_pretrained.sizePolicy().hasHeightForWidth())
        self.pushButton_select_model_pretrained.setSizePolicy(sizePolicy)
        self.pushButton_select_model_pretrained.setMaximumSize(QtCore.QSize(291, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_select_model_pretrained.setFont(font)
        self.pushButton_select_model_pretrained.setObjectName("pushButton_select_model_pretrained")
        self.verticalLayout_2.addWidget(self.pushButton_select_model_pretrained)
        self.pushButton_select_config = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_select_config.sizePolicy().hasHeightForWidth())
        self.pushButton_select_config.setSizePolicy(sizePolicy)
        self.pushButton_select_config.setMaximumSize(QtCore.QSize(291, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_select_config.setFont(font)
        self.pushButton_select_config.setObjectName("pushButton_select_config")
        self.verticalLayout_2.addWidget(self.pushButton_select_config)
        self.pushButton_train = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_train.sizePolicy().hasHeightForWidth())
        self.pushButton_train.setSizePolicy(sizePolicy)
        self.pushButton_train.setMaximumSize(QtCore.QSize(291, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_train.setFont(font)
        self.pushButton_train.setObjectName("pushButton_train")
        self.verticalLayout_2.addWidget(self.pushButton_train)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMaximumSize(QtCore.QSize(291, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setUnderline(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.pushButton_select_model_image = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_select_model_image.sizePolicy().hasHeightForWidth())
        self.pushButton_select_model_image.setSizePolicy(sizePolicy)
        self.pushButton_select_model_image.setMaximumSize(QtCore.QSize(291, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(False)
        self.pushButton_select_model_image.setFont(font)
        self.pushButton_select_model_image.setObjectName("pushButton_select_model_image")
        self.verticalLayout_2.addWidget(self.pushButton_select_model_image)
        self.pushButton_select_image = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_select_image.sizePolicy().hasHeightForWidth())
        self.pushButton_select_image.setSizePolicy(sizePolicy)
        self.pushButton_select_image.setMaximumSize(QtCore.QSize(291, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(False)
        self.pushButton_select_image.setFont(font)
        self.pushButton_select_image.setObjectName("pushButton_select_image")
        self.verticalLayout_2.addWidget(self.pushButton_select_image)
        self.pushButton_select_config_image = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_select_config_image.sizePolicy().hasHeightForWidth())
        self.pushButton_select_config_image.setSizePolicy(sizePolicy)
        self.pushButton_select_config_image.setMaximumSize(QtCore.QSize(291, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(False)
        self.pushButton_select_config_image.setFont(font)
        self.pushButton_select_config_image.setObjectName("pushButton_select_config_image")
        self.verticalLayout_2.addWidget(self.pushButton_select_config_image)
        self.pushButton_image_test = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_image_test.sizePolicy().hasHeightForWidth())
        self.pushButton_image_test.setSizePolicy(sizePolicy)
        self.pushButton_image_test.setMaximumSize(QtCore.QSize(291, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_image_test.setFont(font)
        self.pushButton_image_test.setObjectName("pushButton_image_test")
        self.verticalLayout_2.addWidget(self.pushButton_image_test)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setMaximumSize(QtCore.QSize(291, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setUnderline(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.pushButton_select_model_video = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_select_model_video.sizePolicy().hasHeightForWidth())
        self.pushButton_select_model_video.setSizePolicy(sizePolicy)
        self.pushButton_select_model_video.setMaximumSize(QtCore.QSize(291, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(False)
        self.pushButton_select_model_video.setFont(font)
        self.pushButton_select_model_video.setObjectName("pushButton_select_model_video")
        self.verticalLayout_2.addWidget(self.pushButton_select_model_video)
        self.pushButton_select_video = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_select_video.sizePolicy().hasHeightForWidth())
        self.pushButton_select_video.setSizePolicy(sizePolicy)
        self.pushButton_select_video.setMaximumSize(QtCore.QSize(291, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(False)
        self.pushButton_select_video.setFont(font)
        self.pushButton_select_video.setObjectName("pushButton_select_video")
        self.verticalLayout_2.addWidget(self.pushButton_select_video)
        self.pushButton_select_config_video = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_select_config_video.sizePolicy().hasHeightForWidth())
        self.pushButton_select_config_video.setSizePolicy(sizePolicy)
        self.pushButton_select_config_video.setMaximumSize(QtCore.QSize(291, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(False)
        self.pushButton_select_config_video.setFont(font)
        self.pushButton_select_config_video.setObjectName("pushButton_select_config_video")
        self.verticalLayout_2.addWidget(self.pushButton_select_config_video)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setMinimumSize(QtCore.QSize(0, 0))
        self.label_6.setMaximumSize(QtCore.QSize(82, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.lineEdit_video_save_name = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_video_save_name.sizePolicy().hasHeightForWidth())
        self.lineEdit_video_save_name.setSizePolicy(sizePolicy)
        self.lineEdit_video_save_name.setMaximumSize(QtCore.QSize(158, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_video_save_name.setFont(font)
        self.lineEdit_video_save_name.setObjectName("lineEdit_video_save_name")
        self.horizontalLayout.addWidget(self.lineEdit_video_save_name)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setMaximumSize(QtCore.QSize(37, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.pushButton_video_test = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_video_test.sizePolicy().hasHeightForWidth())
        self.pushButton_video_test.setSizePolicy(sizePolicy)
        self.pushButton_video_test.setMaximumSize(QtCore.QSize(291, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_video_test.setFont(font)
        self.pushButton_video_test.setObjectName("pushButton_video_test")
        self.verticalLayout_2.addWidget(self.pushButton_video_test)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMaximumSize(QtCore.QSize(291, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setUnderline(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.pushButton_clear_terminal = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_clear_terminal.sizePolicy().hasHeightForWidth())
        self.pushButton_clear_terminal.setSizePolicy(sizePolicy)
        self.pushButton_clear_terminal.setMaximumSize(QtCore.QSize(291, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(False)
        self.pushButton_clear_terminal.setFont(font)
        self.pushButton_clear_terminal.setObjectName("pushButton_clear_terminal")
        self.verticalLayout_2.addWidget(self.pushButton_clear_terminal)
        self.pushButton_stop = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_stop.sizePolicy().hasHeightForWidth())
        self.pushButton_stop.setSizePolicy(sizePolicy)
        self.pushButton_stop.setMaximumSize(QtCore.QSize(291, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_stop.setFont(font)
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.verticalLayout_2.addWidget(self.pushButton_stop)
        self.pushButton_reset = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_reset.sizePolicy().hasHeightForWidth())
        self.pushButton_reset.setSizePolicy(sizePolicy)
        self.pushButton_reset.setMaximumSize(QtCore.QSize(291, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(False)
        self.pushButton_reset.setFont(font)
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.verticalLayout_2.addWidget(self.pushButton_reset)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 2, 5, 1)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 1, 0, 1, 1)
        self.display = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.display.sizePolicy().hasHeightForWidth())
        self.display.setSizePolicy(sizePolicy)
        self.display.setMinimumSize(QtCore.QSize(800, 600))
        self.display.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.display.setFont(font)
        self.display.setText("")
        self.display.setScaledContents(False)
        self.display.setObjectName("display")
        self.gridLayout.addWidget(self.display, 2, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 3, 0, 1, 1)
        self.textBrowser_terminal = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_terminal.setMinimumSize(QtCore.QSize(0, 190))
        self.textBrowser_terminal.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textBrowser_terminal.setFont(font)
        self.textBrowser_terminal.setObjectName("textBrowser_terminal")
        self.gridLayout.addWidget(self.textBrowser_terminal, 4, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_7.setText(_translate("MainWindow", "SWIN - GUI"))
        self.label_8.setText(_translate("MainWindow", "Set parameters"))
        self.pushButton_set_parameters.setText(_translate("MainWindow", "Set parameters"))
        self.label.setText(_translate("MainWindow", "Training"))
        self.pushButton_select_model_pretrained.setText(_translate("MainWindow", "Select pretrained model"))
        self.pushButton_select_config.setText(_translate("MainWindow", "Select config"))
        self.pushButton_train.setText(_translate("MainWindow", "Train"))
        self.label_2.setText(_translate("MainWindow", "Image Test"))
        self.pushButton_select_model_image.setText(_translate("MainWindow", "Select model"))
        self.pushButton_select_image.setText(_translate("MainWindow", "Select image"))
        self.pushButton_select_config_image.setText(_translate("MainWindow", "Select config"))
        self.pushButton_image_test.setText(_translate("MainWindow", "Image test"))
        self.label_4.setText(_translate("MainWindow", "Video Test"))
        self.pushButton_select_model_video.setText(_translate("MainWindow", "Select model"))
        self.pushButton_select_video.setText(_translate("MainWindow", "Select video"))
        self.pushButton_select_config_video.setText(_translate("MainWindow", "Select config"))
        self.label_6.setText(_translate("MainWindow", "Save name:"))
        self.lineEdit_video_save_name.setText(_translate("MainWindow", "result"))
        self.label_5.setText(_translate("MainWindow", ".mp4"))
        self.pushButton_video_test.setText(_translate("MainWindow", "Video test"))
        self.label_3.setText(_translate("MainWindow", "Reset"))
        self.pushButton_clear_terminal.setText(_translate("MainWindow", "Clear terminal"))
        self.pushButton_stop.setText(_translate("MainWindow", "Stop"))
        self.pushButton_reset.setText(_translate("MainWindow", "Stop and reset all"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

